base_path: .
preserve_hierarchy: 1
files:
  - source: /faq/en-gb/**/*.md
    translation: /faq/%locale%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        de: de
        es: es
        fr: fr
        it: it
